### ISSUE TITLE
Issue creating initial content set using `npm run wr:cc -- starter`

### ISSUE THREAD

**Issue by thebiglabasky** [wheelroom/wheelroom#107]
Hi!

After configuring wheelroom and pushing the models on the space, running the `npm run wr:cc -- select` command fails:

```
TypeError: Cannot use 'in' operator to search for 'allowedComponents' in undefined
    at /Users/hervelabas/Dev/wheelroom/testwheelroom/node_modules/@wheelroom/wheelroom-plugin-contentful/dist/lib/get-cf-components/content-set-from-wr-content-set.js:16:37
    at Array.forEach (<anonymous>)
    at /Users/hervelabas/Dev/wheelroom/testwheelroom/node_modules/@wheelroom/wheelroom-plugin-contentful/dist/lib/get-cf-components/content-set-from-wr-content-set.js:11:42
    at Array.forEach (<anonymous>)
    at Object.exports.cfContentSetFromWrContentSet (/Users/hervelabas/Dev/wheelroom/testwheelroom/node_modules/@wheelroom/wheelroom-plugin-contentful/dist/lib/get-cf-components/content-set-from-wr-content-set.js:4:34)
    at Object.exports.getCfContentSet (/Users/hervelabas/Dev/wheelroom/testwheelroom/node_modules/@wheelroom/wheelroom-plugin-contentful/dist/lib/get-cf-content-set/get-cf-content-set.js:7:58)
    at Object.<anonymous> (/Users/hervelabas/Dev/wheelroom/testwheelroom/node_modules/@wheelroom/wheelroom-plugin-contentful/dist/lib/initialize-context.js:27:45)
    at Generator.next (<anonymous>)
    at /Users/hervelabas/Dev/wheelroom/testwheelroom/node_modules/@wheelroom/wheelroom-plugin-contentful/dist/lib/initialize-context.js:7:71
    at new Promise (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @wheelroom/boilerplate@3.3.1 wr:cc: `wheelroom --config compiled-config/wheelroom-config.js create-content "starter"`
npm ERR! Exit status 1
```
It seems like a TypeScript strictness-related issue.

Environment: node v14.3.0, MacOS Catalina 10.15.4

**Comment by jaccomeijer** [comment]
The command `npm run wr:cc -- select` should report that the available content sets are `starter` and `example`, unless you've created and compiled your own `select` set. Once we've merged #105, we will look further into this.

Thanks for letting us know!
